management:
  security:
    enabled: false

secuurity:
  basic:
    enabled: false

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true
    show-sql: true


logging:
  pattern:
    file: "%d{HH:mm:ss} %-5p [%c] - %m%n"

  level:
    ROOT: error
    org.springframework: warn
    javax.faces: warn
    org.omnifaces: warn
    org.springframework.security: warn
    org.hibernate: INFO
    org.hibernate.type: trace

  file:
    name: C:\temp\app.log